/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.sun.javafx.geom.Matrix3f;
import dataset.LogicGame;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.TextField;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Word;

/**
 *
 * @author Roibin
 */
public class Game extends javax.swing.JDialog {

    /**
     * Creates new form Game
     * @param parent
     */
    public Game(javax.swing.JDialog parent, boolean modal, int level) {
    int rows=5,column=5;
    Word word = new Word();
    TextField [][] tf = new TextField[rows][column];
        try {
            initComponents();
            setLocationRelativeTo(parent);
            pnMatrix.add(this);
            LogicGame login = new LogicGame();
            login.LGame(level);
//            this.setResizable(false); 
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "El archivo no ha sido encontrado");
            dispose();
            this.setVisible(false);
            Start star = new Start();
            star.setVisible(true);
        }
        
    }

    public Game() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Game(String[][] matrixGame) {
//        this.setResizable(false); 
        this.setBounds(200, 20, 300, 100);
        int row = matrixGame.length;
        int column = matrixGame[0].length;
        TextField[][] matrixTextField = new TextField[row][column];
        int count = 1;
        int x= 0;
        int y = 0;
        for (int i = 0; i < matrixGame.length; i++) {
            for (int j = 0; j < matrixGame[i].length; j++, x++, y++) {
                if(matrixGame[i][j] != null){
                  TextField text = new TextField();
                  text.setText("pureba");
                  this.add(text);
                  text.setVisible(true);
//                matrixTextField[i][j] = new TextField();
//                matrixTextField[i][j].setText(matrixGame[i][j]);
//                matrixTextField[i][j].setLocation(x, y);
//                matrixTextField[i][j].setVisible(true);
//                add(matrixTextField[i][j]);
                }else{
                  TextField text = new TextField();
                  text.setText("pureba");
                  text.setBounds(220, 30, 30, 100);
                  text.setForeground(Color.black);
                  text.setVisible(true);
                  this.add(text);
                  
//                matrixTextField[i][j] = new TextField();
//                matrixTextField[i][j].setText("");
//                this.setBounds(230, 30, 200, 30);
//                matrixTextField[i][j].setForeground(Color.black);
//                matrixTextField[i][j].setVisible(true);
//                add(matrixTextField[i][j]);
                }
            }
        }
    }
    private void initPanel (){
//         int column=3;
//         int rows=3;
//        GridLayout grid = new GridLayout (rows, column);
//        pnMatrix.setLayout(grid);
//         TextField newGridButtom = new TextField();
//            pnMatrix.add(newGridButtom);
//         
//         
//       //  TextField text = new TextField();
// 
    }
//    public void TextField(){
//        for (int i = 0; i < rows; i++) {
//            for (int j = 0; j < column; j++) {
//                tf[rows][column]=new TextField(45*column,32*rows,55,45);
//                tf[rows][column].setName(rows, column);
//                pnMatrix.add(tf[rows][column]);
//            }
//            
//        }
//  
//    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltHorizontal = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ltVertical = new javax.swing.JList<>();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnMatrix.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnMatrixLayout = new javax.swing.GroupLayout(pnMatrix);
        pnMatrix.setLayout(pnMatrixLayout);
        pnMatrixLayout.setHorizontalGroup(
            pnMatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        pnMatrixLayout.setVerticalGroup(
            pnMatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        jButton1.setText("Pistas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ltHorizontal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ltHorizontal.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ltHorizontalValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ltHorizontal);

        ltVertical.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ltVertical);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(pnMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ltHorizontalValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ltHorizontalValueChanged
       
    }//GEN-LAST:event_ltHorizontalValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> ltHorizontal;
    private javax.swing.JList<String> ltVertical;
    private javax.swing.JPanel pnMatrix;
    // End of variables declaration//GEN-END:variables

}