/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.sun.javafx.geom.Matrix3f;
import dataset.LogicGame;
import java.awt.Color;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.TextField;

/**
 *
 * @author Roibin
 */
public class Game extends javax.swing.JDialog {

    /**
     * Creates new form Game
     * @param parent
     */
    public Game(javax.swing.JDialog parent, boolean modal, int level) {
        super(parent, modal);
        try {
            initComponents();
            setLocationRelativeTo(parent);
            
            LogicGame login = new LogicGame();
            login.LGame(level);
//            this.setResizable(false); 
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "El archivo no ha sido encontrado");
            dispose();
            this.setVisible(false);
            Start star = new Start();
            star.setVisible(true);
        }
        
    }

    public Game() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Game(String[][] matrixGame) {
//        this.setResizable(false); 
        this.setBounds(200, 20, 300, 100);
        int row = matrixGame.length;
        int column = matrixGame[0].length;
        TextField[][] matrixTextField = new TextField[row][column];
        int count = 1;
        int x= 0;
        int y = 0;
        for (int i = 0; i < matrixGame.length; i++) {
            for (int j = 0; j < matrixGame[i].length; j++, x++, y++) {
                if(matrixGame[i][j] != null){
                  TextField text = new TextField();
                  text.setText("pureba");
                  this.add(text);
                  text.setVisible(true);
//                matrixTextField[i][j] = new TextField();
//                matrixTextField[i][j].setText(matrixGame[i][j]);
//                matrixTextField[i][j].setLocation(x, y);
//                matrixTextField[i][j].setVisible(true);
//                add(matrixTextField[i][j]);
                }else{
                  TextField text = new TextField();
                  text.setText("pureba");
                  text.setBounds(220, 30, 30, 100);
                  text.setForeground(Color.black);
                  text.setVisible(true);
                  this.add(text);
                  
//                matrixTextField[i][j] = new TextField();
//                matrixTextField[i][j].setText("");
//                this.setBounds(230, 30, 200, 30);
//                matrixTextField[i][j].setForeground(Color.black);
//                matrixTextField[i][j].setVisible(true);
//                add(matrixTextField[i][j]);
                }
            }
        }
    }
    private void initPanel (){
         int column;
//         int rows;
//         GridLayout grid = new GridLayout (rows, columns);
         
         
         TextField text = new TextField();
 
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        jButton1.setText("Pistas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
