/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import model.Word;



/**
 *
 * @author Usuario
 */
public class Levels extends javax.swing.JDialog {

    /**
     * Creates new form Levels
     */
    
    public Levels(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbLevels = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        cbLevels2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 24)); // NOI18N
        jLabel1.setText("Seleccione el nivel del juego");
        getContentPane().add(jLabel1);

        cbLevels.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        cbLevels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil", "Muy Dificil", " " }));
        cbLevels.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLevelsItemStateChanged(evt);
            }
        });
        cbLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLevelsActionPerformed(evt);
            }
        });
        getContentPane().add(cbLevels);

        jButton1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        btBack.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        btBack.setText("Regresar");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        getContentPane().add(btBack);

        cbLevels2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        cbLevels2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil ", "Medio", "Dificil", "Muy Dificil" }));
        cbLevels2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLevels2ActionPerformed(evt);
            }
        });
        getContentPane().add(cbLevels2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPlayActionPerformed(java.awt.event.ActionEvent evt) {                                       
       int i = cbLevels.getSelectedIndex();
       
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Game game = new Game(this,true, 1);
        game.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbLevelsActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    } 


private void cbLevelsItemStateChanged(java.awt.event.ItemEvent evt) {                                          
        
       
        
    }    
    
    

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void cbLevels2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLevels2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLevels2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JComboBox<String> cbLevels;
    private javax.swing.JComboBox<String> cbLevels2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
